#!/bin/bash

# 直接部署命令 - 手动执行
echo "=== AWS EC2 部署命令 ==="
echo ""
echo "1. 等待实例完全启动 (约2-3分钟)"
echo "   检查实例状态: aws ec2 describe-instances --instance-ids i-036a06c4b70462f6c"
echo ""
echo "2. 上传代码到EC2"
echo "   需要您的SSH密钥文件路径，例如: ~/.ssh/my-key.pem"
echo "   scp -i ~/.ssh/my-key.pem -r backend/ frontend/ database/ docker-compose.yml env.example ec2-user@98.87.249.41:/home/ec2-user/app/"
echo ""
echo "3. SSH连接到EC2"
echo "   ssh -i ~/.ssh/my-key.pem ec2-user@98.87.249.41"
echo ""
echo "4. 在EC2上执行以下命令:"
echo "   cd /home/ec2-user/app"
echo "   cp env.example .env"
echo "   nano .env  # 添加您的OpenAI API密钥"
echo "   docker-compose up --build -d"
echo ""
echo "5. 检查服务状态"
echo "   docker-compose ps"
echo "   docker-compose logs"
echo ""
echo "6. 访问应用"
echo "   前端: http://98.87.249.41:3000"
echo "   后端API: http://98.87.249.41:3001"
echo "   健康检查: http://98.87.249.41:3001/api/health"
echo ""
echo "=== 重要提醒 ==="
echo "- 请确保您有SSH密钥文件 (my-key.pem)"
echo "- 需要在.env文件中添加OpenAI API密钥"
echo "- 首次部署可能需要5-10分钟"
